on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-falt: false
      matrix:
        x: [ 0, 1, 2, 3, 4, 5, 6, 7 ]
        y: [ 0, 1, 2, 3, 4, 5, 6, 7 ]
    steps:
      - run: touch test
      - uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.x }}:${{ matrix.y }}"
          path: test
